import type { CapabilityContract, JsonSchema } from "./contracts.ts";

const object = (required: string[], properties: Record<string, JsonSchema>): JsonSchema => ({
  type: "object" as const,
  required,
  additionalProperties: false,
  properties,
});

/**
 * The maintained seed catalog. These contracts are provider-neutral and are
 * intentionally smaller than any provider SDK. Additions are Core changes.
 */
export const CORE_CAPABILITY_CATALOG: readonly CapabilityContract[] = [
  {
    id: "knowledge.search",
    version: "3.0.0",
    description: "Search the active Company Knowledge snapshot and return bounded cited evidence.",
    mode: "read",
    minimumRisk: "R0",
    inputSchema: object(["query"], {
      query: { type: "string", minLength: 1, maxLength: 1_000 },
      limit: { type: "integer", minimum: 1, maximum: 20 },
      mode: { type: "string", enum: ["lexical", "hybrid"] },
    }),
    outputSchema: object(["query", "snapshot_hash", "hits", "gaps", "mode", "degradations"], {
      query: { type: "string" },
      snapshot_hash: { type: ["string", "null"] },
      hits: {
        type: "array",
        maxItems: 20,
        items: object(["score", "excerpt", "signals", "citation"], {
          score: { type: "number" },
          excerpt: { type: "string" },
          signals: { type: "array", items: { type: "string", enum: ["stale", "contested"] } },
          lexical_rank: { type: "integer", minimum: 1 },
          semantic_rank: { type: "integer", minimum: 1 },
          citation: object(["snapshot_hash", "path", "fragment_id", "heading", "start_line", "end_line", "digest"], {
            snapshot_hash: { type: "string" },
            path: { type: "string" },
            fragment_id: { type: "string" },
            heading: { type: "string" },
            start_line: { type: "integer" },
            end_line: { type: "integer" },
            digest: { type: "string" },
          }),
        }),
      },
      gaps: { type: "array", items: { type: "string", enum: ["no-active-snapshot", "no-results"] } },
      mode: { type: "string", enum: ["lexical", "hybrid"] },
      degradations: { type: "array", items: { type: "string", enum: ["embedding-disabled", "embedding-unavailable", "vector-index-unavailable"] } },
    }),
    idempotency: "none",
    evidence: ["snapshot_hash", "result_count", "connector"],
  },
  {
    id: "knowledge.get",
    version: "3.0.0",
    description: "Fetch one exact OKF document from the active Company Knowledge snapshot.",
    mode: "read",
    minimumRisk: "R0",
    inputSchema: object(["path"], {
      path: { type: "string", minLength: 1, maxLength: 1_000 },
    }),
    outputSchema: object(["found"], {
      found: { type: "boolean" },
      snapshot_hash: { type: "string" },
      document: { type: "object" },
    }),
    idempotency: "none",
    evidence: ["snapshot_hash", "path", "found", "connector"],
  },
  {
    id: "knowledge.traverse",
    version: "3.0.0",
    description: "Traverse bounded inbound or outbound OKF links from one exact document path.",
    mode: "read",
    minimumRisk: "R0",
    inputSchema: object(["path"], {
      path: { type: "string", minLength: 1, maxLength: 1_000 },
      direction: { type: "string", enum: ["outbound", "inbound", "both"] },
      max_depth: { type: "integer", minimum: 0, maximum: 5 },
      max_nodes: { type: "integer", minimum: 1, maximum: 100 },
    }),
    outputSchema: object(["snapshot_hash", "start_path", "direction", "paths", "truncated", "gaps"], {
      snapshot_hash: { type: ["string", "null"] },
      start_path: { type: "string" },
      direction: { type: "string", enum: ["outbound", "inbound", "both"] },
      paths: { type: "array", maxItems: 100, items: { type: "object" } },
      truncated: { type: "boolean" },
      gaps: { type: "array", items: { type: "string", enum: ["no-active-snapshot", "unknown-start-path"] } },
    }),
    idempotency: "none",
    evidence: ["snapshot_hash", "start_path", "node_count", "truncated", "connector"],
  },
  {
    id: "artifact.publish",
    version: "1.0.0",
    description: "Publish one immutable content artifact and return its address.",
    mode: "effect",
    minimumRisk: "R3",
    inputSchema: object(["artifact_id", "content", "content_type"], {
      artifact_id: { type: "string", minLength: 1 },
      content: { type: "string" },
      content_type: { type: "string", minLength: 1 },
    }),
    outputSchema: object(["artifact_id", "url", "digest"], {
      artifact_id: { type: "string" },
      url: { type: "string" },
      digest: { type: "string" },
    }),
    idempotency: "required",
    evidence: ["artifact_id", "url", "digest", "connector"],
  },
  {
    id: "marketing-campaign.launch",
    version: "1.0.0",
    description: "Launch a bounded marketing campaign from approved assets and spend limits.",
    mode: "effect",
    minimumRisk: "R4",
    inputSchema: object(["campaign_key", "daily_budget", "days", "assets"], {
      campaign_key: { type: "string", minLength: 1 },
      daily_budget: { type: "number", minimum: 0 },
      days: { type: "integer", minimum: 1 },
      assets: { type: "array", items: { type: "string" } },
    }),
    outputSchema: object(["campaign_id", "status", "max_spend", "simulated"], {
      campaign_id: { type: "string" },
      status: { type: "string" },
      max_spend: { type: "number" },
      simulated: { type: "boolean" },
    }),
    idempotency: "required",
    evidence: ["campaign_id", "status", "max_spend", "simulated", "connector"],
  },
  {
    id: "marketing-campaign.read-report",
    version: "1.0.0",
    description: "Read normalized campaign delivery and conversion facts.",
    mode: "read",
    minimumRisk: "R0",
    inputSchema: object(["campaign_key"], {
      campaign_key: { type: "string", minLength: 1 },
    }),
    outputSchema: { type: "object" },
    idempotency: "none",
    evidence: ["campaign_id", "observed_at", "connector"],
  },
  {
    id: "marketing-campaign.stop-asset",
    version: "1.0.0",
    description: "Stop one campaign asset without increasing the approved maximum spend.",
    mode: "effect",
    minimumRisk: "R2",
    inputSchema: object(["campaign_key", "asset"], {
      campaign_key: { type: "string", minLength: 1 },
      asset: { type: "string", minLength: 1 },
    }),
    outputSchema: { type: "object" },
    idempotency: "required",
    evidence: ["campaign_id", "stopped_asset", "max_spend", "connector"],
  },
  {
    id: "conversion.record",
    version: "1.0.0",
    description: "Record a conversion attributed to one campaign asset.",
    mode: "effect",
    minimumRisk: "R0",
    inputSchema: object(["campaign_key", "asset", "conversion_id"], {
      campaign_key: { type: "string", minLength: 1 },
      asset: { type: "string", minLength: 1 },
      conversion_id: { type: "string", minLength: 1 },
    }),
    outputSchema: { type: "object" },
    idempotency: "required",
    evidence: ["conversion_id", "recorded", "connector"],
  },
  {
    id: "records.query",
    version: "1.0.0",
    description: "Query one authorized Company Records projection without exposing database or provider access.",
    mode: "read",
    minimumRisk: "R0",
    inputSchema: object(["projection_id"], {
      projection_id: { type: "string", minLength: 1, maxLength: 63 },
      filters: { type: "object" },
      limit: { type: "integer", minimum: 1, maximum: 200 },
      cursor: { type: "string", minLength: 1, maxLength: 1_000 },
    }),
    outputSchema: object(["projection_id", "rows", "observed_at", "fresh_until", "access_decision"], {
      projection_id: { type: "string" },
      rows: { type: "array", maxItems: 200, items: { type: "object" } },
      next_cursor: { type: "string" },
      observed_at: { type: "string" },
      fresh_until: { type: "string" },
      access_decision: { type: "object" },
    }),
    idempotency: "none",
    evidence: ["projection_id", "row_count", "observed_at", "fresh_until", "access_decision", "connector"],
  },
  {
    id: "work-item.read",
    version: "1.0.0",
    description: "Read one bounded provider-neutral work item through an exact Instance resource binding.",
    mode: "read",
    minimumRisk: "R0",
    inputSchema: object(["resource_binding", "work_item_id"], {
      resource_binding: { type: "string", minLength: 1, maxLength: 63 },
      work_item_id: { type: "string", minLength: 1, maxLength: 255 },
      fields: { type: "array", maxItems: 100, items: { type: "string", minLength: 1, maxLength: 127 } },
    }),
    outputSchema: object(["work_item", "provider_version", "observed_at"], {
      work_item: { type: "object" },
      provider_version: { type: "string" },
      observed_at: { type: "string" },
    }),
    idempotency: "none",
    evidence: ["resource_binding", "work_item_id", "provider_version", "observed_at", "connector"],
  },
  {
    id: "work-item.update",
    version: "1.0.0",
    description: "Update explicitly named fields on one provider-neutral work item and return read-after-write evidence.",
    mode: "effect",
    minimumRisk: "R2",
    inputSchema: object(["resource_binding", "work_item_id", "changes", "expected_version"], {
      resource_binding: { type: "string", minLength: 1, maxLength: 63 },
      work_item_id: { type: "string", minLength: 1, maxLength: 255 },
      changes: { type: "object" },
      expected_version: { type: "string", minLength: 1, maxLength: 255 },
    }),
    outputSchema: object(["work_item", "previous_version", "provider_version", "changed_fields"], {
      work_item: { type: "object" },
      previous_version: { type: "string" },
      provider_version: { type: "string" },
      changed_fields: { type: "array", items: { type: "string" } },
    }),
    idempotency: "required",
    evidence: ["resource_binding", "work_item_id", "previous_version", "provider_version", "changed_fields", "connector"],
  },
  {
    id: "work-item.comment",
    version: "1.0.0",
    description: "Append one bounded attributed comment to a provider-neutral work item.",
    mode: "effect",
    minimumRisk: "R2",
    inputSchema: object(["resource_binding", "work_item_id", "body"], {
      resource_binding: { type: "string", minLength: 1, maxLength: 63 },
      work_item_id: { type: "string", minLength: 1, maxLength: 255 },
      body: { type: "string", minLength: 1, maxLength: 10_000 },
    }),
    outputSchema: object(["comment_id", "work_item_id", "provider_version", "created_at"], {
      comment_id: { type: "string" },
      work_item_id: { type: "string" },
      provider_version: { type: "string" },
      created_at: { type: "string" },
    }),
    idempotency: "required",
    evidence: ["resource_binding", "work_item_id", "comment_id", "provider_version", "created_at", "connector"],
  },
  {
    id: "communication.message.publish",
    version: "1.0.0",
    description: "Publish one bounded internal message through an exact Instance destination binding.",
    mode: "effect",
    minimumRisk: "R2",
    inputSchema: object(["destination_binding", "content"], {
      destination_binding: { type: "string", minLength: 1, maxLength: 63 },
      content: { type: "string", minLength: 1, maxLength: 20_000 },
      thread_reference: { type: "string", minLength: 1, maxLength: 1_000 },
      format: { type: "string", enum: ["plain-text", "provider-markdown"] },
    }),
    outputSchema: object(["message_id", "destination_binding", "published_at"], {
      message_id: { type: "string" },
      destination_binding: { type: "string" },
      thread_reference: { type: "string" },
      published_at: { type: "string" },
    }),
    idempotency: "required",
    evidence: ["destination_binding", "message_id", "thread_reference", "published_at", "connector"],
  },
] as const;
